name: weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  pretty_dio_logger: ^1.3.1
  internet_connection_checker_plus: ^2.2.0
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  location: ^5.0.3
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.8.0
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_background_asset.png
    - assets/images/house_icon_src.png
    - assets/images/mostly_clear_icon.png
    - assets/images/sunny_icon.png
    - assets/images/cloudy_icon.png
    - assets/images/heavy_rain_icon.png
    - assets/images/rain_icon.png
    - assets/images/snow_icon.png
    - assets/images/storm_icon.png
    - assets/images/flurries_icon.png
    - assets/images/fog_icon.png
    - assets/lottie/loader.json
    - assets/lottie/network_error.json
